#  Tags are assigned to the corresponding resources being created.
#    "application" represents team name, e.g. 'probate', 'divorce', use 'core' for platform infrastructure.
#    "businessArea" represents the business area this application belongs to, one of CFT / Crime / Cross-Cutting.
#  Further docs: https://tools.hmcts.net/confluence/display/DCO/Tagging+v0.4

sds-platform:
  team: "platform operations"
  namespace: ""
  slack:
    contact_channel: "#platops-help"
    build_notices_channel: "#platops-build-notices"
  tags:
    application: "core"
    businessArea: "Cross-Cutting"

cft-platform:
  team: "platform operations"
  namespace: ""
  slack:
    contact_channel: "#platops-help"
    build_notices_channel: "#platops-build-notices"
  tags:
    application: "core"
    businessArea: "CFT"

slack-help-bot:
  team: "platform operations"
  namespace: ""
  slack:
    contact_channel: "#platops-help"
    build_notices_channel: "#platops-build-notices"
  tags:
    application: "core"
    businessArea: "CFT"

app-proxy:
  team: "platform operations"
  namespace: ""
  slack:
    contact_channel: "#platops-help"
    build_notices_channel: "#platops-build-notices"
  tags:
    application: "core"
    businessArea: "Cross-Cutting"

response:
  team: "platform operations"
  namespace: "response"
  slack:
    contact_channel: "#platops-help"
    build_notices_channel: "#platops-build-notices"
  tags:
    application: "core"
    businessArea: "CFT"

soc:
  team: "soc"
  namespace: ""
  slack:
    contact_channel: "#sec-ops"
    build_notices_channel: ""
  tags:
    application: "security"
    businessArea: "Cross-Cutting"

ethos:
  team: "ethos"
  namespace: ""
  slack:
    contact_channel: "#ethos-repl-service"
    build_notices_channel: ""
  tags:
    application: "ethos"
    businessArea: "Cross-Cutting"

heritage:
  team: "heritage"
  namespace: ""
  slack:
    contact_channel: ""
    build_notices_channel: ""
  tags:
    application: "bais"
    businessArea: "Cross-Cutting"

mi:
  team: "mi"
  namespace: ""
  slack:
    contact_channel: "#mi-data-platform"
    build_notices_channel: ""
  tags:
    application: "management-information"
    businessArea: "Cross-Cutting"

dc:
  team: "dc"
  namespace: ""
  slack:
    contact_channel: ""
    build_notices_channel: ""
  tags:
    application: "data-catalogue"
    businessArea: "Cross-Cutting"

pet:
  team: "pet"
  namespace: ""
  slack:
    contact_channel: "#pet-devops"
    build_notices_channel: ""
  tags:
    application: "pet"
    businessArea: "Cross-Cutting"

robotics:
  team: "robotics"
  namespace: ""
  slack:
    contact_channel: "#robotics"
    build_notices_channel: ""
  tags:
    application: "robotics"
    businessArea: "Cross-Cutting"

mgmt:
  team: "mgmt"
  namespace: ""
  slack:
    contact_channel: "#platops-help"
    build_notices_channel: ""
  tags:
    application: "core"
    businessArea: "Cross-Cutting"

hub:
  team: "platform operations"
  namespace: ""
  slack:
    contact_channel: "#platops-help"
    build_notices_channel: "#platops-build-notices"
  tags:
    application: "core"
    businessArea: "Cross-Cutting"

sds-jenkins:
  team: "platform operations"
  namespace: ""
  slack:
    contact_channel: "#platops-help"
    build_notices_channel: "#platops-build-notices"
  tags:
    application: "core"
    businessArea: "Cross-Cutting"

cft-jenkins:
  team: "platform operations"
  namespace: ""
  slack:
    contact_channel: "#platops-help"
    build_notices_channel: "#platops-build-notices"
  tags:
    application: "core"
    businessArea: "CFT"

mailrelay:
  team: "platform operations"
  namespace: ""
  slack:
    contact_channel: "#platops-help"
    build_notices_channel: "#platops-build-notices"
  tags:
    application: "core"
    businessArea: "Cross-Cutting"
hmi:
  team: "hmi"
  namespace: ""
  slack:
    contact_channel: "#vh-devops"
    build_notices_channel: ""
  tags:
    application: "hearings-management-interface"
    businessArea: "Cross-Cutting"
toffee:
  team: "platform operations"
  namespace: ""
  slack:
    contact_channel: "#platops-help"
    build_notices_channel: "#platops-build-notices"
  tags:
    application: "core"
    businessArea: "Cross-Cutting"
juror-digital:
  team: "platform operations"
  namespace: ""
  slack:
    contact_channel: ""
    build_notices_channel: ""
  tags:
    application: "juror-digital"
    businessArea: "Cross-Cutting"
ctsc:
  team: "CTSC"
  namespace: "ctsc"
  slack:
    contact_channel: "#ctsc-master-builds"
    build_notices_channel: "#ctsc-master-builds"
  tags:
    application: "courts-tribunals-service-centre"
    businessArea: "Cross-Cutting"
vh:
  team: "Video Hearings"
  namespace: "vh"
  slack:
    contact_channel: "#vh-devops"
    build_notices_channel: "#vh-builds"
  tags:
    application: "video-hearings-service"
    businessArea: "Cross-Cutting"
wowza:
  team: "Video Hearings"
  namespace: "vh"
  slack:
    contact_channel: "#vh-devops"
    build_notices_channel: "#vh-builds"
  tags:
    application: "video-hearings-service"
    businessArea: "Cross-Cutting"
pip:
  team: "Publishing and Information"
  namespace: "pip"
  slack:
    contact_channel: "#vh-devops"
    build_notices_channel: "#vh-builds"
  tags:
    application: "publishing-information-service"
    businessArea: "Cross-Cutting"
pre:
  team: "Pre Recorded Evidence"
  namespace: ""
  slack:
    contact_channel: ""
    build_notices_channel: "#pre-builds"
  tags:
    application: "pre-recorded-evidence"
    businessArea: "Cross-Cutting"
cvp:
  team: "Cloud Video Platform"
  namespace: "cvp"
  slack:
    contact_channel: "#vh-devops"
    build_notices_channel: "#vh-builds"
  tags:
    application: "cloud-video-platform"
    businessArea: "Cross-Cutting"
shared-image-gallery:
  team: "platform operations"
  namespace: ""
  slack:
    contact_channel: "#platops-help"
    build_notices_channel: "#platops-build-notices"
  tags:
    application: "core"
    businessArea: "Cross-Cutting"

caps:
  team: "Centralised Attachment of earnings Payment System"
  namespace: ""
  slack:
    contact_channel: ""
    build_notices_channel: ""
  tags:
    application: "caps"
    businessArea: "Cross-Cutting"

pcol:
  team: "Possession Claim On-Line"
  namespace: ""
  slack:
    contact_channel: ""
    build_notices_channel: ""
  tags:
    application: "pcol"
    businessArea: "Cross-Cutting"

caseman:
  team: "Case Management of County Courts"
  namespace: ""
  slack:
    contact_channel: ""
    build_notices_channel: ""
  tags:
    application: "caseman"
    businessArea: "Cross-Cutting"

mcol:
  team: "Money Claim On-Line"
  namespace: ""
  slack:
    contact_channel: ""
    build_notices_channel: ""
  tags:
    application: "mcol"
    businessArea: "Cross-Cutting"

bais:
  team: "BAU Integration Service"
  namespace: ""
  slack:
    contact_channel: ""
    build_notices_channel: ""
  tags:
    application: "bais"
    businessArea: "Cross-Cutting"

darts-idam:
  team: "Digital Audio Recording Transcriber and Storage Identity Access Management"
  namespace: ""
  slack:
    contact_channel: ""
    build_notices_channel: ""
  tags:
    application: "darts-idam"
    businessArea: "Cross-Cutting"

sdt:
  team: "Secure Data Transfer"
  namespace: ""
  slack:
    contact_channel: ""
    build_notices_channel: ""
  tags:
    application: "heritage-secure-data-transfer"
    businessArea: "Cross-Cutting"

template-management:
  team: "template-management"
  namespace: "docmosis"
  slack:
    contact_channel: "docmosis"
    build_notices_channel: "docmosis-builds"
  tags:
    application: "core"
    businessArea: "CFT"

small-systems-migrations:
  team: "heritage-power-apps"
  namespace: ""
  slack:
    contact_channel: ""
    build_notices_channel: ""
  tags:
    application: "heritage-power-apps"
    businessArea: "Cross-Cutting"

rcjg-migrations:
  team: "heritage-power-apps"
  namespace: ""
  slack:
    contact_channel: ""
    build_notices_channel: ""
  tags:
    application: "heritage-power-apps"
    businessArea: "Cross-Cutting"

neuvector:
  team: "platform operations"
  namespace: ""
  slack:
    contact_channel: "#platops-help"
    build_notices_channel: "#platops-build-notices"
  tags:
    application: "core"
    businessArea: "Cross-Cutting"

cft-neuvector:
  team: "platform operations"
  namespace: ""
  slack:
    contact_channel: "#platops-help"
    build_notices_channel: "#platops-build-notices"
  tags:
    application: "core"
    businessArea: "CFT"

core-infra:
  team: "platform operations"
  namespace: ""
  slack:
    contact_channel: "#platops-help"
    build_notices_channel: "#platops-build-notices"
  tags:
    application: "core"
    businessArea: "CFT"

arm:
  team: "Archiving with Records Management"
  namespace: ""
  slack:
    contact_channel: ""
    build_notices_channel: ""
  tags:
    application: "archive-with-records-management"
    businessArea: "Cross-Cutting"

enterprise:
  team: "platform operations"
  namespace: ""
  slack:
    contact_channel: "#platops-help"
    build_notices_channel: "#platops-build-notices"
  tags:
    application: "core"
    businessArea: "Cross-Cutting"

martha:
  team: "MARTHA"
  namespace: ""
  slack:
    contact_channel: ""
    build_notices_channel: ""
  tags:
    application: "martha"
    businessArea: "cross-cutting"

allpay:
  team: "AllPay"
  namespace: ""
  slack:
    contact_channel: ""
    build_notices_channel: ""
  tags:
    application: "allpay"
    businessArea: "cross-cutting"

crime-platform:
  team: "Crime"
  namespace: ""
  slack:
    contact_channel: ""
    build_notices_channel: ""
  tags:
    application: "core"
    businessArea: "Crime"

aad-domain-services:
  team: "platform operations"
  namespace: ""
  slack:
    contact_channel: "#platops-help"
    build_notices_channel: ""
  tags:
    application: "core"
    businessArea: "Cross-Cutting"

glimr:
  team: "GLiMR"
  namespace: ""
  slack:
    contact_channel: ""
    build_notices_channel: ""
  tags:
    application: "glimr"
    businessArea: "cross-cutting"

crime-portal:
  team: "Crime Portal"
  namespace: ""
  slack:
    contact_channel: "#dtspo-orange"
    build_notices_channel: ""
  tags:
    application: "crime-portal"
    businessArea: "cross-cutting"

dlrm-ingest:
  team: "DLRM Data Ingestion"
  namespace: ""
  slack:
    contact_channel: "#dtspo-orange"
    build_notices_channel: ""
  tags:
    application: "dlrm-data-ingest"
    businessArea: "cross-cutting"

docmosis:
  team: "platform operations"
  namespace: ""
  slack:
    contact_channel: "#platops-help"
    build_notices_channel: "#platops-build-notices"
  tags:
    application: "docmosis"
    businessArea: "CFT"

sdrs:
  team: "SDRS"
  namespace: ""
  slack:
    contact_channel: "#dtspo-orange"
    build_notices_channel: ""
  tags:
    application: "sdrs"
    businessArea: "cross-cutting"

sdp-data-analytics:
  team: "SDP Data Analytics"
  namespace: ""
  slack:
    contact_channel: "#dtspo-orange"
    build_notices_channel: ""
  tags:
    application: "sdp-data-analytics"
    businessArea: "cross-cutting"

atlassian:
  team: "platform operations"
  namespace: ""
  slack:
    contact_channel: "#platops-help"
    build_notices_channel: "#platops-build-notices"
  tags:
    application: "atlassian"
    businessArea: "Cross-Cutting"

baubais:
  team: "platform operations"
  namespace: ""
  slack:
    contact_channel: "#platops-help"
    build_notices_channel: "#platops-build-notices"
  tags:
    application: "baubais"
    businessArea: "Cross-Cutting"

ccd:
  team: "ccd-devops"
  namespace: ""
  slack:
    contact_channel: "#ccd-devops"
    build_notices_channel: ""
  tags:
    application: "core-case-data"
    businessArea: "CFT"

sct-rm:
  team: "sct-resource-management"
  namespace: ""
  slack:
    contact_channel: ""
    build_notices_channel: ""
  tags:
    application: "sct-rm"
    businessArea: "Cross-Cutting"

gaps2:
  team: "heritage"
  namespace: ""
  slack:
    contact_channel: "#platops-help"
    build_notices_channel: ""
  tags:
    application: "gaps2"
    businessArea: "Cross-Cutting"

beetroot:
  team: "platform operations"
  namespace: ""
  slack:
    contact_channel: "#platops-help"
    build_notices_channel: "#platops-build-notices"
  tags:
    application: "core"
    businessArea: "Cross-Cutting"

dtsse:
  team: "platform operations"
  namespace: ""
  slack:
    contact_channel: "#platops-help"
    build_notices_channel: "#platops-build-notices"
  tags:
    application: "core"
    businessArea: "CFT"

cactus:
  team: "cactus"
  namespace: ""
  slack:
    contact_channel: "#cactus-migration"
    build_notices_channel: "#cactus-migration"
  tags:
    application: "cactus"
    businessArea: "CFT"
